/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Erzachel Senna Rizky Farezi 24060123130065
 */
import java.util.*;
import javax.swing.DefaultListModel;

public class GUI extends javax.swing.JFrame {
    DefaultListModel<String> dlm; 
    List<String> list = new ArrayList<>();
    Set<String> set = new HashSet<>();
    Map<Integer, String> map = new HashMap<>();
    int mapKey = 1;

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        dlm = new DefaultListModel<>();
        jListItem.setModel(dlm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListItem = new javax.swing.JList<>();
        jClearAll = new javax.swing.JButton();
        jSavetoList = new javax.swing.JButton();
        jInsertdataList = new javax.swing.JButton();
        jSavetoSet = new javax.swing.JButton();
        jInsertdataSet = new javax.swing.JButton();
        jSavetoMap = new javax.swing.JButton();
        jInsertdataMap = new javax.swing.JButton();
        jTextFieldItem = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jDelete = new javax.swing.JButton();
        jAdd = new javax.swing.JButton();
        jUpdate = new javax.swing.JButton();
        jDataList = new javax.swing.JLabel();
        jDataSet = new javax.swing.JLabel();
        jDataMap = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jListItem.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListItem);

        jClearAll.setText("Clear All");
        jClearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearAllActionPerformed(evt);
            }
        });

        jSavetoList.setText("Save to List ->");
        jSavetoList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSavetoListActionPerformed(evt);
            }
        });

        jInsertdataList.setText("<- Insert data List");
        jInsertdataList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInsertdataListActionPerformed(evt);
            }
        });

        jSavetoSet.setText("Save to Set ->");
        jSavetoSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSavetoSetActionPerformed(evt);
            }
        });

        jInsertdataSet.setText("<- Insert data Set");
        jInsertdataSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInsertdataSetActionPerformed(evt);
            }
        });

        jSavetoMap.setText("Save to Map ->");
        jSavetoMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSavetoMapActionPerformed(evt);
            }
        });

        jInsertdataMap.setText("<- Insert data Map");
        jInsertdataMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInsertdataMapActionPerformed(evt);
            }
        });

        jLabel2.setText("Item Name :");

        jDelete.setText("Delete");
        jDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteActionPerformed(evt);
            }
        });

        jAdd.setText("Add");
        jAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddActionPerformed(evt);
            }
        });

        jUpdate.setText("Update");
        jUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateActionPerformed(evt);
            }
        });

        jDataList.setText("Data Tersimpan = 0");

        jDataSet.setText("Data Tersimpan = 0");

        jDataMap.setText("Data Tersimpan = 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jClearAll, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jInsertdataList, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSavetoList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSavetoSet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jInsertdataSet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSavetoMap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jInsertdataMap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jUpdate)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDataList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDataSet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDataMap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDelete)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldItem, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(153, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSavetoList)
                            .addComponent(jDataList))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jInsertdataList)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSavetoSet)
                            .addComponent(jDataSet))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jInsertdataSet)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSavetoMap)
                            .addComponent(jDataMap))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jInsertdataMap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUpdate)
                    .addComponent(jDelete)
                    .addComponent(jAdd)
                    .addComponent(jClearAll))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearAllActionPerformed
        dlm.clear();
    }//GEN-LAST:event_jClearAllActionPerformed

    private void jSavetoListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSavetoListActionPerformed
        if (!list.isEmpty()){
            list.clear();
        }
        
        for (int i=0; i < dlm.getSize(); i++){
            list.add(dlm.getElementAt(i));
        }
        
        updateDataList();
    }//GEN-LAST:event_jSavetoListActionPerformed

    private void jDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteActionPerformed
        int index = jListItem.getSelectedIndex();
        dlm.removeElementAt(index);
        
        jTextFieldItem.setText("");
    }//GEN-LAST:event_jDeleteActionPerformed

    private void jUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateActionPerformed
        int index = jListItem.getSelectedIndex();
        String selected = jTextFieldItem.getText();
        dlm.setElementAt(selected, index);
        
        jTextFieldItem.setText("");
    }//GEN-LAST:event_jUpdateActionPerformed

    private void jInsertdataListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInsertdataListActionPerformed
        dlm.clear();
        
        for(String item : list){
            dlm.addElement(item);
        }
    }//GEN-LAST:event_jInsertdataListActionPerformed

    private void jAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddActionPerformed
        addItem(jTextFieldItem.getText());
        
        jTextFieldItem.setText("");
    }//GEN-LAST:event_jAddActionPerformed

    private void jSavetoSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSavetoSetActionPerformed
        if (!set.isEmpty()){
            set.clear();
        }
        
        for (int i=0; i < dlm.getSize(); i++){
            set.add(dlm.getElementAt(i));
        }
        
        updateDataSet();
    }//GEN-LAST:event_jSavetoSetActionPerformed

    private void jInsertdataSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInsertdataSetActionPerformed
        dlm.clear();
        
        for(String item : set){
            dlm.addElement(item);
        }
    }//GEN-LAST:event_jInsertdataSetActionPerformed

    private void jSavetoMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSavetoMapActionPerformed
        if (!map.isEmpty()){
            map.clear();
        }
        
        for (int i=0; i < dlm.getSize(); i++){
            map.put(mapKey++, dlm.getElementAt(i));
        }
        
        updateDataMap();
    }//GEN-LAST:event_jSavetoMapActionPerformed

    private void jInsertdataMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInsertdataMapActionPerformed
        dlm.clear();
        
        for(String item : map.values()){
            dlm.addElement(item);
        }
    }//GEN-LAST:event_jInsertdataMapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAdd;
    private javax.swing.JButton jClearAll;
    private javax.swing.JLabel jDataList;
    private javax.swing.JLabel jDataMap;
    private javax.swing.JLabel jDataSet;
    private javax.swing.JButton jDelete;
    private javax.swing.JButton jInsertdataList;
    private javax.swing.JButton jInsertdataMap;
    private javax.swing.JButton jInsertdataSet;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jListItem;
    private javax.swing.JButton jSavetoList;
    private javax.swing.JButton jSavetoMap;
    private javax.swing.JButton jSavetoSet;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldItem;
    private javax.swing.JButton jUpdate;
    // End of variables declaration//GEN-END:variables

    private void addItem(String namaItem) {
        dlm.addElement(namaItem);
    }

    private void updateDataList() {
        jDataList.setText("Data Tersimpan = " + list.size());
    }

    private void updateDataSet() {
        jDataSet.setText("Data Tersimpan = " + set.size());
    }

    private void updateDataMap() {
        jDataMap.setText("Data Tersimpan = " + map.size());
    }
}
